# Server
server:
    port: 8082

# Spring
spring:
    application:
        name: armazenamento-video
    profiles:
        active: dev
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}

queue:
    video: videos-status
    zip: zips-gerados

storage:
    s3:
        bucket: fiap-videos-processados

cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: us-east-1
